[package]
name = "ca"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib-egui-rs = { workspace = true }
rand = { workspace = true }

# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui = "0.32.0"
egui_extras = { version = "0.32.0", features = ["default", "image"] }
