[package]
name = "fertilization"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib-egui-rs = { path = "../../../raylib-egui-rs", features = ["raygui"] }
rand = { workspace = true } 
genetic = { path = "../genetic" }
